branch-defaults:
  main:
    environment: ps-tool-v2-auth-env
global:
  application_name: PS-TOOL-V2-AUTH-SERVICE
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: ca-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
